### ISSUE TITLE
✅ TODO List

### ISSUE THREAD

**Issue by DiscordAnaxes** [DiscordAnaxes/Anaxes.xyz#6]
- [x] Implement Twitter API
- [x] Dark Mode/Light Mode toggle?
- [x] Implement GitHub API
- [x] Implement Lanyard API
- [x] Fix mobile view of the website
- [x] Convert JavaScript to TypeScript
